spring:
  datasource:
    url: jdbc:mysql://hayabusa.proxy.rlwy.net:22484/seafood_dummy_test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: oHBjtqnDzrmazriXyQZHyXoCXAphMbSK
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: local-dev-secret-key-please-change-this-to-a-long-random-string-1234567890
  access-token-expiration: 3600000
  admin-access-token-expiration: 1800000
  refresh-token-expiration: 604800000