spring:
  application:
    name: seeat-api
  profiles:
    active: local

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.seeat.seeatapi: DEBUG
    org.hibernate.SQL: DEBUG